### ISSUE TITLE
[Question] Where is the code for ble_store_config_init

### ISSUE THREAD

**Issue by alberk8** [h2zero/esp-nimble-cpp#107]
What does function suppose to do?
[ble_store_config_init()](https://github.com/h2zero/esp-nimble-cpp/blob/05ac9deaead7e05865fd7aaca5f9f8747d00a99a/src/NimBLEDevice.cpp#L905)

**Comment by h2zero** [comment]
It loads the stores ble data from the flash. This function is in the nimble core code.

**Comment by alberk8** [comment]
Thank you for replying.
