### ISSUE TITLE
[Question] StartSecurity / ble_gap_security_initiate in Central and Periperal

### ISSUE THREAD

**Issue by alberk8** [h2zero/esp-nimble-cpp#108]
Hi,

I find this in the Event Subscribe of [BleServer](https://github.com/h2zero/esp-nimble-cpp/blob/05ac9deaead7e05865fd7aaca5f9f8747d00a99a/src/NimBLEServer.cpp#L425) which is odd (what appends if the Authentication is needed when Characteristics is only a read or write),

On the [Central](https://github.com/h2zero/esp-nimble-cpp/blob/88562bb31084c9978521e4dfbb98ae52e5a2e859/src/NimBLEClient.cpp#L239) where is this called, this there an example?

Thank you.

**Comment by h2zero** [comment]
This is only called when a central subscribes to notifications and the peripheral characteristic flags are set to use security.
