### ISSUE TITLE
Advertising after client connect.

### ISSUE THREAD

**Issue by enhany** [h2zero/esp-nimble-cpp#125]
Hello,

I try to allow multiple clients, so I call NimBLEDevice::startAdvertising in NimBLEServerCallbacks::onConnect.
But advertising stop itself in few seconds after call.
Is it a bug or what I do wrong?

**Comment by h2zero** [comment]
Not sure how I missed this but that sounds like a bug. Advertising should not stop unless there is a connection or the time expires. If this is still an issue for you please let me know.

**Comment by h2zero** [comment]
Closing this as there has been no response.
