### ISSUE TITLE
NimBLE_extended_server encrypt

### ISSUE THREAD

**Issue by enhany** [h2zero/esp-nimble-cpp#126]
Hello.

When using NimBLE_extended_server  example with:
```
	NimBLEDevice::setSecurityIOCap(BLE_HS_IO_NO_INPUT_OUTPUT);
	NimBLEDevice::setSecurityAuth(BLE_SM_PAIR_AUTHREQ_BOND | BLE_SM_PAIR_AUTHREQ_MITM | BLE_SM_PAIR_AUTHREQ_SC);
```

then not possible to bond. Any bond request just disconnect client.

**Comment by h2zero** [comment]
Please try again with only setting bond flag: `NimBLEDevice::setSecurityAuth(BLE_SM_PAIR_AUTHREQ_BOND);`

**Comment by h2zero** [comment]
Closing as there has been no response.
