### ISSUE TITLE
Create UUID

### ISSUE THREAD

**Issue by AquaMCU** [h2zero/esp-nimble-cpp#136]
I need a little help.

I follow your documentation and have trouble creating a NimBLEUUID for the scale service of my BT device. It has the ID 0x180f.
When I try to implement that with the following line:

 if(advertisedDevice->isAdvertisingService(NimBLEUUID( 0x180f )))

I get the following error:

error: call of overloaded 'NimBLEUUID(int)' is ambiguous

I can not wrap my brain around this. Can you please guide me in the right direction?

THX Oliver

**Comment by h2zero** [comment]
Try specifying the type of the hex value. `(uint16_t)0x180f`.
