### ISSUE TITLE
driver error on Windows

### ISSUE THREAD

**Issue by 13Pixel** [h2zero/esp-nimble-cpp#137]
Hello, I'm having some issues with HID and windows. On Linux everything work fine.

I modified Simple ble server example and added NimBLEHIDDevice. Problem is that on Windows I get driver error, on this bluetooth device. 

Does anyone had similar issues?

Thanks.

**Comment by thomasMEBaker** [comment]
@13Pixel - I am experiencing the same issue. Did you find a fix for this?

**Comment by 13Pixel** [comment]
Unfortunately no, Couldn't find way to fix this, so put it on hold till I'll have time to figure it out.

**Comment by h2zero** [comment]
Do you have bonding enabled? I believe it's a requirement in windows.

**Comment by thomasMEBaker** [comment]
As in "Persist the BLE Bonding keys in NVS" within the Nimble Options?

**Comment by h2zero** [comment]
You should enable that as well as set the device to bond by calling `NimBLEDevice::setSecurityAuth(true, false, true);` You'll also need to call `NimBLEDevice::startSecurity` in the on connect callback or set the characteristic properties to require encryption.
