### ISSUE TITLE
Not getting passkey events in custom gap handler

### ISSUE THREAD

**Issue by finger563** [h2zero/esp-nimble-cpp#146]
I'm not getting `BLE_GAP_EVENT_PASSKEY_ACTION` in my custom gap event handler (but I am getting the other event), is that expected? Relevant code [here](https://github.com/esp-cpp/espp/blob/main/components/gfps_service/src/nearby_ble.cpp#L82)

_Originally posted by @finger563 in https://github.com/h2zero/esp-nimble-cpp/pull/117#issuecomment-1984916612_

**Comment by h2zero** [comment]
Hmm, I'm not sure why that isn't being sent, possibly missing the call in NimBLE.

**Comment by h2zero** [comment]
@finger563 I have confirmed this to be an upstream issue. 
There should be a call here to `ble_gap_event_listener_call(&event);` here: https://github.com/espressif/esp-nimble/blob/d53c988a93aef899a4198fdf69c828309f312c1e/nimble/host/src/ble_gap.c#L7116

To

**Comment by h2zero** [comment]
Closing this as it is an upstream issue.
