### ISSUE TITLE
Why your deviceInfoService the pnp characteristic vid pid version high byte on low position🙃

### ISSUE THREAD

**Issue by qingwa2009** [h2zero/esp-nimble-cpp#153]
void NimBLEHIDDevice::pnp(uint8_t sig, uint16_t vid, uint16_t pid, uint16_t version) {
	uint8_t pnp[] = { sig, (uint8_t) (vid >> 8), (uint8_t) vid, (uint8_t) (pid >> 8), (uint8_t) pid, (uint8_t) (version >> 8), (uint8_t) version };
	m_pnpCharacteristic->setValue(pnp, sizeof(pnp));
}

**Comment by h2zero** [comment]
hello @qingwa2009, the code for this class was adopted from the original library and has not been changed materially for this repo. I'm not very familiar with the HID requirements and I would appreciate any suggestions or PR's that would improve this.

**Comment by h2zero** [comment]
Fixed in 6fa3783
