### ISSUE TITLE
Add esp-nimble-cpp to esp component registry

### ISSUE THREAD

**Issue by tecera** [h2zero/esp-nimble-cpp#172]
Espressif has recently(ish) created the component registry (https://components.espressif.com/). This makes it really easy for users of the library to automatically update the library without needing to use git submodules or complicated workflows. The package can be automatically published to the registry using a Github Action as well.

Would you be interested in supporting this?

**Comment by h2zero** [comment]
This has finally be completed, you can now find it on the registry: https://components.espressif.com/components/h2zero/esp-nimble-cpp/versions/2.0.0
