### ISSUE TITLE
Add library to PlatformIO

### ISSUE THREAD

**Issue by burnsie-la** [h2zero/esp-nimble-cpp#175]
Is it possible for you to add this to PlatformIO like you did with the Arduino version: https://registry.platformio.org/libraries/h2zero/NimBLE-Arduino

**Comment by h2zero** [comment]
Hello @burnsie-la, yes I will look to do this at next release.

**Comment by h2zero** [comment]
Sorry it took so long but I have finally released version 2.0.0 and published it to platformio here https://registry.platformio.org/libraries/h2zero/esp-nimble-cpp
