### ISSUE TITLE
UUID compare problem with 16bits

### ISSUE THREAD

**Issue by Zmmfly** [h2zero/esp-nimble-cpp#190]
master commit: `209f70a0839b18e59e97517c7c9276eefe53430b`

In the function `bool NimBLEUUID::operator==(const NimBLEUUID& rhs) const`, I found that if it is not a 128-bit uuid, it will compare ptr, which will probably never be equal.

https://github.com/h2zero/esp-nimble-cpp/blob/209f70a0839b18e59e97517c7c9276eefe53430b/src/NimBLEUUID.cpp#L290-L292

The `getValue` from here:

https://github.com/h2zero/esp-nimble-cpp/blob/209f70a0839b18e59e97517c7c9276eefe53430b/src/NimBLEUUID.cpp#L139-L150

I'm sorry, I can't submit PR in the current environment.

**Comment by h2zero** [comment]
Thanks! I will fix this shortly. Lots of big changes happening so the feedback is paramount.
