### ISSUE TITLE
tiny log clean up

### ISSUE THREAD

**Issue by mitchjs** [h2zero/esp-nimble-cpp#23]
@h2zero, question when i see in the log

```
I NimBLECharacteristic: "New subscribe value for conn: 0 val: 1"
I NimBLEServer: "subscribe event; cur_notify=1\n value handle; " "val_handle=56\n"
```
the \n
how about change line 306 in NimBLEServer.cpp to:
`NIMBLE_LOGI(LOG_TAG, "subscribe event; attr_handle=%d, subscribed: %s", event->subscribe.attr_handle, (event->subscribe.cur_notify ? "true":"false"));;`
looks nicer :)

`I NimBLEServer: "subscribe event; attr_handle=61, subscribed: false"`

reason i bring up, i got issue with client app... subscribing... so i was actually paying attention to log..
*bug in client app... 

keep up the great work...

**Comment by h2zero** [comment]
Lol, yes I think there are a few of these still hanging around. I'll clean this up in the onSubscribe PR. Thanks!
