### ISSUE TITLE
NimBLEClient::connect not using expected peer address

### ISSUE THREAD

**Issue by thekurtovic** [h2zero/esp-nimble-cpp#242]
Occasionally I'm getting connection failures seemingly due to the target peer address being incorrectly set.
I've only noticed it when reusing client objects, but I always manually set the peer address. Added some extra log messages in NimBLEClient to track the address along the way.
Testing on master with esp32-s3.

```
I [142994][main.cpp:257] BLE adv (-57 db, phy 1 0) Name: , Address: e3:e4:5b:75:ad:36
D [143016][main.cpp:280] Reusing client, set addr->e3:e4:5b:75:ad:36
W (143026) NimBLEClient: setPeerAddress->35:3a:34:65:3a:33
W (143036) NimBLEClient: connect set addr->35:3a:34:65:3a:33
E (143037) NimBLEClient: Failed to connect to 35:3a:34:65:3a:33, rc=3;
E [143047][main:293] Failed to connect
```
```
void ScanCallbacks::onResult(const NimBLEAdvertisedDevice *adv)
{
    ....
    auto client = NimBLEDevice::getDisconnectedClient();
    if (!client) {
        client = NimBLEDevice::createClient(adv->getAddress());
        if (!client) {
            // TODO state error handling..
            LOG_E("Failed to create client");
            return;
        }
    } else {
        LOG_D("Reusing client, set addr->%s", adv->getAddress().toString().c_str());
        client->setPeerAddress(adv->getAddress());
    }
  
    client->setClientCallbacks(&clientCB, false);
    client->setConnectionParams(6, 6, 0, 400);
    if (!client->connect(true, true, true))
        LOG_E("Failed to connect");
    ....
}
```

Adding `const NimBLEAddress address = adv->getAddress();` at the start of `onResult` seems to avoid the issue, but I'll let it run for the day to confirm.

**Comment by h2zero** [comment]
@thekurtovic I'm not able to reproduce this, I did find another issue though. I copied the code you provided into my onResult callback and restarted the server device multiple times and could reconnect each time without issue.

**Comment by thekurtovic** [comment]
Thanks for checking. I believe this only started the other day, I must have done something stupid in my code.
I'll roll things back on my end and double check with a simplified `onResult` handler.
Closing for now assuming user error.

**Comment by thekurtovic** [comment]
I call `NimBLEDevice::getScan()->stop();` near the start of the `onResult` callback after validating the advertised device. It looks like the pointer which is passed to the `onResult` callback becomes invalid since stopping the scan clears the results when `m_maxResults` is 0.

If I modify `NimBLEScan::handleGapEvent` like so, then the issue is avoided.
`pScan->m_pScanCallbacks->on...(advertisedDevice);`
to
```
NimBLEAdvertisedDevice dev = *advertisedDevice;
pScan->m_pScanCallbacks->on...(&dev);
```

**Comment by h2zero** [comment]
I'd suggest handling this in your callback the same way, validate the device, make a copy, then stop the scan.
