### ISSUE TITLE
small issue with latest master commits

### ISSUE THREAD

**Issue by mitchjs** [h2zero/esp-nimble-cpp#27]
when compiling...

../components/esp-nimble-cpp/src/NimBLEAddress.cpp:173:38: error: '%d' directive output may be truncated writing between 1 and 3 bytes into a region of size 2 [-Werror=format-truncation=]
     snprintf(buffer, sizeof(buffer), "%02x:%02x:%02x:%02x:%02x:%02x type: %d",
                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../components/esp-nimble-cpp/src/NimBLEAddress.cpp:173:38: note: directive argument in the range [0, 255]
../components/esp-nimble-cpp/src/NimBLEAddress.cpp:173:13: note: 'snprintf' output between 26 and 28 bytes into a destination of size 26
     snprintf(buffer, sizeof(buffer), "%02x:%02x:%02x:%02x:%02x:%02x type: %d",
     ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                      m_address[5], m_address[4], m_address[3],
                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                      m_address[2], m_address[1], m_address[0],
                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                      m_addrType);
                                      ~~~~~~~~~~~


i changed char buffer[26]; to char buffer[28];

keep up the great work... this seems to get better and better feature wise (course im only using server)
mitch

**Comment by h2zero** [comment]
Damn, the one time I don't check against idf v4 lol. Thanks for the heads up, will fix right now.
