### ISSUE TITLE
Buffer index issue in handling writes to Characteristics

### ISSUE THREAD

**Issue by szroland** [h2zero/esp-nimble-cpp#29]
I believe there is an error in processing writes to Characteristics when the value spans a longer chain of memory buffers, there is an extra -1 in the index when adding more data from the chain in NimBLECharacteristic.cpp line 243:

```c
memcpy(&buf[len-1], next->om_data, next->om_len);
```

I added a pull request with the fix, #30.

**Comment by h2zero** [comment]
Looks like some troubleshooting code sneaked in. 

Thanks! Will merge right away.
