### ISSUE TITLE
Lower Memory footprint

### ISSUE THREAD

**Issue by 0xFEEDC0DE64** [h2zero/esp-nimble-cpp#45]
Hi,
I added the simple example to our existing firmware code and sadly, nimble seems to eat up all the free memory?

when I start adding more and more characteristics, will this go even more down?

(Before the first outage, bluetooth was completely disabled in sdkconfig and nimble was not linked to the application, after the short break all the memory is gone)
![image](https://user-images.githubusercontent.com/10342708/119959906-b65caa00-bfa4-11eb-8099-6e34c3039570.png)

the free_8 memory is measured with `heap_caps_get_largest_free_block(MALLOC_CAP_INTERNAL|MALLOC_CAP_8BIT)` and the free_32 is measured with `heap_caps_get_free_size(MALLOC_CAP_INTERNAL|MALLOC_CAP_32BIT)`

**Comment by h2zero** [comment]
Hi @0xFEEDC0DE64, I am assuming you are also using wifi in this project? NimBLE is very small on it's own but when the co-exist libraries are linked as well there is significantly more RAM consumed (still much less than with bluedroid). This is sadly something that is out of our control as it is a part of IDF. Heap use can be reduced with NimBLE config settings in sdkconfig, turning off the BLE roles you are not using and reducing the max connections and and memory block sizes will help.

**Comment by 0xFEEDC0DE64** [comment]
WiFi was used at the same time, and i disabled all unneeded ble features with similar ram results, I can register 1 or 2 characteristics before everything crashes down. Looks like we won't add bluetooth or ble soon in our products (at least not without a second esp32 on the board :) )

**Comment by h2zero** [comment]
That's unfortunate. I don't know what all is in your device for memory consumption. but the benchmark I have for basic BLE and WiFi combination there is 170k heap leftover. If that's no enough for the project then I'd suggest a PSRAM module instead of another esp32 :)
