### ISSUE TITLE
Compilation fails if CONFIG_BT_NIMBLE_ROLE_BROADCASTER not defined

### ISSUE THREAD

**Issue by arjanmels** [h2zero/esp-nimble-cpp#49]
If CONFIG_BT_NIMBLE_ROLE_BROADCASTER is not defined then startAdevrtising, SstopAdvertising are not defined nin NimBLEDevice, but are used in other parts.

**Comment by h2zero** [comment]
If you are not using the broadcaster role then you should also disable the peripheral role and it will work. I'll address this with a macro in a future patch.
