### ISSUE TITLE
Compilation fails with idf 4.3/gcc 8.4

### ISSUE THREAD

**Issue by arjanmels** [h2zero/esp-nimble-cpp#50]
A number of compile failures occurs (probably due to switch to gcc 8.4):
invalid conversion from 'const void*' to 'void*' [-fpermissive] in NMEBLEAdvertising
invalid conversion from 'int' to 'esp_log_level_t' [-fpermissive] in log_common.h

I worked around it by adding "idf_build_set_property(COMPILE_OPTIONS "-fpermissive" APPEND)" to the CMakeLists.txt

**Comment by h2zero** [comment]
I do not get any compile errors with 4.3. Are you using the master branch of this repo?

**Comment by arjanmels** [comment]
I am using 1.2.0 release.

The master branch have an error on freetos.cpp file missing.

Arjan

Op wo 14 jul. 2021 18:33 schreef h2zero ***@***.***>:

**Comment by h2zero** [comment]
Yes, that has been corrected, please try with latest master commit.

**Comment by arjanmels** [comment]
Great! 

Almost, I get:
'CONFIG_BTDM_SCAN_DUPL_CACHE_SIZE' was not declared in this scope
'CONFIG_BTDM_SCAN_DUPL_TYPE' was not declared in this scope

Which are called:
CONFIG_BT_CTRL_SCAN_DUPL_CACHE_SIZE
CONFIG_BT_CTRL_SCAN_DUPL_TYPE
in my sdkconfig. I updated the nimconfig_rename.h file
`
#if defined(CONFIG_SCAN_DUPLICATE_TYPE) && !defined(CONFIG_BTDM_SCAN_DUPL_TYPE)
#define CONFIG_BTDM_SCAN_DUPL_TYPE CONFIG_SCAN_DUPLICATE_TYPE 
#endif

#if defined(CONFIG_BT_CTRL_SCAN_DUPL_TYPE) && !defined(CONFIG_BTDM_SCAN_DUPL_TYPE)
#define CONFIG_BTDM_SCAN_DUPL_TYPE CONFIG_BT_CTRL_SCAN_DUPL_TYPE 
#endif

#if defined(CONFIG_DUPLICATE_SCAN_CACHE_SIZE) && !defined(CONFIG_BTDM_SCAN_DUPL_CACHE_SIZE)
#define CONFIG_BTDM_SCAN_DUPL_CACHE_SIZE CONFIG_DUPLICATE_SCAN_CACHE_SIZE 
#endif

#if defined(CONFIG_BT_CTRL_SCAN_DUPL_CACHE_SIZE) && !defined(CONFIG_BTDM_SCAN_DUPL_CACHE_SIZE)
#define CONFIG_BTDM_SCAN_DUPL_CACHE_SIZE CONFIG_BT_CTRL_SCAN_DUPL_CACHE_SIZE 
#endif

`
and now it works. 

Thanks a lot!
