### ISSUE TITLE
ESP32-S2 support?

### ISSUE THREAD

**Issue by jtwaleson** [h2zero/esp-nimble-cpp#57]
When trying to build for ESP32S2 I get the following error:

    Component esp-nimble-cpp-master only supports targets:
    esp32;esp32s3;esp32c3

Are there any plans to support S2?

**Comment by h2zero** [comment]
Esp32s2 does not support Bluetooth/BLE, it is WiFi only.

**Comment by jtwaleson** [comment]
> Esp32s2 does not support Bluetooth/BLE, it is WiFi only.

Hahaha, I am an idiot. Thanks for the quick reply! I hope this thread will help some others.
