### ISSUE TITLE
onMTUChanged vs onMtuChanged...

### ISSUE THREAD

**Issue by davidlehrian** [h2zero/esp-nimble-cpp#64]
Thanks for the work on this library.  I'm using the ESP-IDF and saw a 174k reduction in flash usage and 13k reduction in ram usage on my project.  

I did experience an issue when migrating from Bluedroid to Nimble that isn't documented here that was rather frustrating.  The issue was the callback in NimBLEServer for onMTUChanged.  While I was able to catch that the signature changed from that in BLEServer, I did not catch that the method name changed in capitalization.  I fixed the signature and then pulled my hair out trying to figure out why the callback wasn't being made.  I finally caught it hours later and it works fine, but I wanted to mention this as it could be fixed with a macro or at least mentioned in the migration document, that is, assuming you noticed that you changed the method name ;-)  

NimBLEServer.h
    virtual void onMTUChange(uint16_t MTU, ble_gap_conn_desc* desc);

BLEServer.h
    virtual void onMtuChanged(BLEServer* pServer, esp_ble_gatts_cb_param_t* param);

**Comment by h2zero** [comment]
Thanks for pointing this out, and sorry for your frustrations. I didn't realize the original library had this callback, I must have missed it or it was added later. If you would like to PR with a macro to alias this I would be glad to merge it.
