### ISSUE TITLE
Autofragmentation characteristic transfers

### ISSUE THREAD

**Issue by mickeyl** [h2zero/esp-nimble-cpp#86]
Due to [L2CAP not really working](https://github.com/espressif/esp-idf/issues/9044) yet, I'm looking to transfer larger stream of data (i.e. up to 4KB) via consecutive READs (and WRITEs for the response) to a characteristic and then deliver the whole payload to my upper layers.

What's the best way to do this using esp-nimble-cpp? Do you perhaps have classes ready that can assist me with this task?

**Comment by h2zero** [comment]
I don't have any specific classes for this but it could be done quite simply with the existing framework.

There are multiple ways to handle this but packetizing would seem the easiest. For speed you would want to limit the packet sizes to the MTU size - 3. Calculate from there how many packets you'll need to send and specify the number of packets remaining at the beginning of each packet sent. The peer device could then construct the data as each packet arrives, stripping the header of course. 

The only tricky part may be timing of write calls, you may want to user write with response for this to make it easy, it would be slower though.
