### ISSUE TITLE
Install docs: where is 'Bluetooth host'?

### ISSUE THREAD

**Issue by petemillermultimedia** [h2zero/esp-nimble-cpp#89]
Under Installation ESP-IDF v4.0+:

in menuconfig, where is "Bluetooth host"? At the top menu I see only Component -> config

Under Component -> config there is a
    Bluetooth -->
    ESP-NimBLEW-CPP configuration -->

Under Bluetooth-> there is
    [*] Bluetooth
         Bluetooth controller -->
    [*] Bluetooth Enable -->
    
I can't find a 'Bluetooth host' item anywhere.

**Comment by h2zero** [comment]
It should be under the `Bluetooth Enable` menu item.

**Comment by petemillermultimedia** [comment]
OK. If you enable []Bluedroid Enable, the NimBLE option is not visible. Unchecking that item reveals the NimBLE option. Awkward.
