### ISSUE TITLE
Question: how to use bootInput and bootOutput in HID Kbd

### ISSUE THREAD

**Issue by CrowdedFuzzball** [h2zero/esp-nimble-cpp#90]
Hello!

Could you please share a little example how to use bootInput and bootOuput characteristics?
I understand how to create them and add to HID service, but can't understand how to handle data correctly.

Thank you.

**Comment by h2zero** [comment]
I don't have any answer for you sadly. I don't know much about the HID protocols. Hopefully someone who does can answer this for you.

**Comment by h2zero** [comment]
Closing as stale.
